// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/graph/tensor_shape.proto

package com.tencent.angel.core.graph;

public final class TensorShapeProtos {
  private TensorShapeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TensorShapeProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:angel.TensorShapeProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
     */
    java.util.List<com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim> 
        getDimList();
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
     */
    com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim getDim(int index);
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
     */
    int getDimCount();
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
     */
    java.util.List<? extends com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.DimOrBuilder> 
        getDimOrBuilderList();
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
     */
    com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.DimOrBuilder getDimOrBuilder(
        int index);

    /**
     * <pre>
     * If true, the number of dimensions in the shape is unknown.
     * If true, "dim.size()" must be 0.
     * </pre>
     *
     * <code>bool unknown_rank = 3;</code>
     */
    boolean getUnknownRank();
  }
  /**
   * <pre>
   * Dimensions of a tensor.
   * </pre>
   *
   * Protobuf type {@code angel.TensorShapeProto}
   */
  public  static final class TensorShapeProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:angel.TensorShapeProto)
      TensorShapeProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TensorShapeProto.newBuilder() to construct.
    private TensorShapeProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TensorShapeProto() {
      dim_ = java.util.Collections.emptyList();
      unknownRank_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TensorShapeProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                dim_ = new java.util.ArrayList<com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim>();
                mutable_bitField0_ |= 0x00000001;
              }
              dim_.add(
                  input.readMessage(com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.parser(), extensionRegistry));
              break;
            }
            case 24: {

              unknownRank_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          dim_ = java.util.Collections.unmodifiableList(dim_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.angel.core.graph.TensorShapeProtos.internal_static_angel_TensorShapeProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.angel.core.graph.TensorShapeProtos.internal_static_angel_TensorShapeProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.class, com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Builder.class);
    }

    public interface DimOrBuilder extends
        // @@protoc_insertion_point(interface_extends:angel.TensorShapeProto.Dim)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * Size of the tensor in that dimension.
       * This value must be &gt;= -1, but values of -1 are reserved for "unknown"
       * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
       * that work with TensorShapeProto may fail at runtime when deserializing
       * a TensorShapeProto containing a dim value of -1.
       * </pre>
       *
       * <code>int64 size = 1;</code>
       */
      long getSize();

      /**
       * <pre>
       * Optional name of the tensor dimension.
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      java.lang.String getName();
      /**
       * <pre>
       * Optional name of the tensor dimension.
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * <pre>
     * One dimension of the tensor.
     * </pre>
     *
     * Protobuf type {@code angel.TensorShapeProto.Dim}
     */
    public  static final class Dim extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:angel.TensorShapeProto.Dim)
        DimOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Dim.newBuilder() to construct.
      private Dim(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Dim() {
        size_ = 0L;
        name_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Dim(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                size_ = input.readInt64();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.angel.core.graph.TensorShapeProtos.internal_static_angel_TensorShapeProto_Dim_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.angel.core.graph.TensorShapeProtos.internal_static_angel_TensorShapeProto_Dim_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.class, com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.Builder.class);
      }

      public static final int SIZE_FIELD_NUMBER = 1;
      private long size_;
      /**
       * <pre>
       * Size of the tensor in that dimension.
       * This value must be &gt;= -1, but values of -1 are reserved for "unknown"
       * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
       * that work with TensorShapeProto may fail at runtime when deserializing
       * a TensorShapeProto containing a dim value of -1.
       * </pre>
       *
       * <code>int64 size = 1;</code>
       */
      public long getSize() {
        return size_;
      }

      public static final int NAME_FIELD_NUMBER = 2;
      private volatile java.lang.Object name_;
      /**
       * <pre>
       * Optional name of the tensor dimension.
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * Optional name of the tensor dimension.
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (size_ != 0L) {
          output.writeInt64(1, size_);
        }
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (size_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, size_);
        }
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim)) {
          return super.equals(obj);
        }
        com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim other = (com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim) obj;

        boolean result = true;
        result = result && (getSize()
            == other.getSize());
        result = result && getName()
            .equals(other.getName());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SIZE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSize());
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * One dimension of the tensor.
       * </pre>
       *
       * Protobuf type {@code angel.TensorShapeProto.Dim}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:angel.TensorShapeProto.Dim)
          com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.DimOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.tencent.angel.core.graph.TensorShapeProtos.internal_static_angel_TensorShapeProto_Dim_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.tencent.angel.core.graph.TensorShapeProtos.internal_static_angel_TensorShapeProto_Dim_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.class, com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.Builder.class);
        }

        // Construct using com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          size_ = 0L;

          name_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.tencent.angel.core.graph.TensorShapeProtos.internal_static_angel_TensorShapeProto_Dim_descriptor;
        }

        public com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim getDefaultInstanceForType() {
          return com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.getDefaultInstance();
        }

        public com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim build() {
          com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim buildPartial() {
          com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim result = new com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim(this);
          result.size_ = size_;
          result.name_ = name_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim) {
            return mergeFrom((com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim other) {
          if (other == com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.getDefaultInstance()) return this;
          if (other.getSize() != 0L) {
            setSize(other.getSize());
          }
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long size_ ;
        /**
         * <pre>
         * Size of the tensor in that dimension.
         * This value must be &gt;= -1, but values of -1 are reserved for "unknown"
         * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
         * that work with TensorShapeProto may fail at runtime when deserializing
         * a TensorShapeProto containing a dim value of -1.
         * </pre>
         *
         * <code>int64 size = 1;</code>
         */
        public long getSize() {
          return size_;
        }
        /**
         * <pre>
         * Size of the tensor in that dimension.
         * This value must be &gt;= -1, but values of -1 are reserved for "unknown"
         * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
         * that work with TensorShapeProto may fail at runtime when deserializing
         * a TensorShapeProto containing a dim value of -1.
         * </pre>
         *
         * <code>int64 size = 1;</code>
         */
        public Builder setSize(long value) {
          
          size_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Size of the tensor in that dimension.
         * This value must be &gt;= -1, but values of -1 are reserved for "unknown"
         * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
         * that work with TensorShapeProto may fail at runtime when deserializing
         * a TensorShapeProto containing a dim value of -1.
         * </pre>
         *
         * <code>int64 size = 1;</code>
         */
        public Builder clearSize() {
          
          size_ = 0L;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <pre>
         * Optional name of the tensor dimension.
         * </pre>
         *
         * <code>string name = 2;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * Optional name of the tensor dimension.
         * </pre>
         *
         * <code>string name = 2;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * Optional name of the tensor dimension.
         * </pre>
         *
         * <code>string name = 2;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Optional name of the tensor dimension.
         * </pre>
         *
         * <code>string name = 2;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Optional name of the tensor dimension.
         * </pre>
         *
         * <code>string name = 2;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:angel.TensorShapeProto.Dim)
      }

      // @@protoc_insertion_point(class_scope:angel.TensorShapeProto.Dim)
      private static final com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim();
      }

      public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Dim>
          PARSER = new com.google.protobuf.AbstractParser<Dim>() {
        public Dim parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Dim(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Dim> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Dim> getParserForType() {
        return PARSER;
      }

      public com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int DIM_FIELD_NUMBER = 2;
    private java.util.List<com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim> dim_;
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
     */
    public java.util.List<com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim> getDimList() {
      return dim_;
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
     */
    public java.util.List<? extends com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.DimOrBuilder> 
        getDimOrBuilderList() {
      return dim_;
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
     */
    public int getDimCount() {
      return dim_.size();
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
     */
    public com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim getDim(int index) {
      return dim_.get(index);
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
     */
    public com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.DimOrBuilder getDimOrBuilder(
        int index) {
      return dim_.get(index);
    }

    public static final int UNKNOWN_RANK_FIELD_NUMBER = 3;
    private boolean unknownRank_;
    /**
     * <pre>
     * If true, the number of dimensions in the shape is unknown.
     * If true, "dim.size()" must be 0.
     * </pre>
     *
     * <code>bool unknown_rank = 3;</code>
     */
    public boolean getUnknownRank() {
      return unknownRank_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < dim_.size(); i++) {
        output.writeMessage(2, dim_.get(i));
      }
      if (unknownRank_ != false) {
        output.writeBool(3, unknownRank_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < dim_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, dim_.get(i));
      }
      if (unknownRank_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, unknownRank_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto)) {
        return super.equals(obj);
      }
      com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto other = (com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto) obj;

      boolean result = true;
      result = result && getDimList()
          .equals(other.getDimList());
      result = result && (getUnknownRank()
          == other.getUnknownRank());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDimCount() > 0) {
        hash = (37 * hash) + DIM_FIELD_NUMBER;
        hash = (53 * hash) + getDimList().hashCode();
      }
      hash = (37 * hash) + UNKNOWN_RANK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUnknownRank());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Dimensions of a tensor.
     * </pre>
     *
     * Protobuf type {@code angel.TensorShapeProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:angel.TensorShapeProto)
        com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.angel.core.graph.TensorShapeProtos.internal_static_angel_TensorShapeProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.angel.core.graph.TensorShapeProtos.internal_static_angel_TensorShapeProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.class, com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Builder.class);
      }

      // Construct using com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDimFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (dimBuilder_ == null) {
          dim_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dimBuilder_.clear();
        }
        unknownRank_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.angel.core.graph.TensorShapeProtos.internal_static_angel_TensorShapeProto_descriptor;
      }

      public com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto getDefaultInstanceForType() {
        return com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.getDefaultInstance();
      }

      public com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto build() {
        com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto buildPartial() {
        com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto result = new com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (dimBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            dim_ = java.util.Collections.unmodifiableList(dim_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dim_ = dim_;
        } else {
          result.dim_ = dimBuilder_.build();
        }
        result.unknownRank_ = unknownRank_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto) {
          return mergeFrom((com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto other) {
        if (other == com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.getDefaultInstance()) return this;
        if (dimBuilder_ == null) {
          if (!other.dim_.isEmpty()) {
            if (dim_.isEmpty()) {
              dim_ = other.dim_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDimIsMutable();
              dim_.addAll(other.dim_);
            }
            onChanged();
          }
        } else {
          if (!other.dim_.isEmpty()) {
            if (dimBuilder_.isEmpty()) {
              dimBuilder_.dispose();
              dimBuilder_ = null;
              dim_ = other.dim_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dimBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDimFieldBuilder() : null;
            } else {
              dimBuilder_.addAllMessages(other.dim_);
            }
          }
        }
        if (other.getUnknownRank() != false) {
          setUnknownRank(other.getUnknownRank());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim> dim_ =
        java.util.Collections.emptyList();
      private void ensureDimIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          dim_ = new java.util.ArrayList<com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim>(dim_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim, com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.Builder, com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.DimOrBuilder> dimBuilder_;

      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public java.util.List<com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim> getDimList() {
        if (dimBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dim_);
        } else {
          return dimBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public int getDimCount() {
        if (dimBuilder_ == null) {
          return dim_.size();
        } else {
          return dimBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim getDim(int index) {
        if (dimBuilder_ == null) {
          return dim_.get(index);
        } else {
          return dimBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public Builder setDim(
          int index, com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim value) {
        if (dimBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDimIsMutable();
          dim_.set(index, value);
          onChanged();
        } else {
          dimBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public Builder setDim(
          int index, com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.Builder builderForValue) {
        if (dimBuilder_ == null) {
          ensureDimIsMutable();
          dim_.set(index, builderForValue.build());
          onChanged();
        } else {
          dimBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public Builder addDim(com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim value) {
        if (dimBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDimIsMutable();
          dim_.add(value);
          onChanged();
        } else {
          dimBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public Builder addDim(
          int index, com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim value) {
        if (dimBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDimIsMutable();
          dim_.add(index, value);
          onChanged();
        } else {
          dimBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public Builder addDim(
          com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.Builder builderForValue) {
        if (dimBuilder_ == null) {
          ensureDimIsMutable();
          dim_.add(builderForValue.build());
          onChanged();
        } else {
          dimBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public Builder addDim(
          int index, com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.Builder builderForValue) {
        if (dimBuilder_ == null) {
          ensureDimIsMutable();
          dim_.add(index, builderForValue.build());
          onChanged();
        } else {
          dimBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public Builder addAllDim(
          java.lang.Iterable<? extends com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim> values) {
        if (dimBuilder_ == null) {
          ensureDimIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dim_);
          onChanged();
        } else {
          dimBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public Builder clearDim() {
        if (dimBuilder_ == null) {
          dim_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dimBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public Builder removeDim(int index) {
        if (dimBuilder_ == null) {
          ensureDimIsMutable();
          dim_.remove(index);
          onChanged();
        } else {
          dimBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.Builder getDimBuilder(
          int index) {
        return getDimFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.DimOrBuilder getDimOrBuilder(
          int index) {
        if (dimBuilder_ == null) {
          return dim_.get(index);  } else {
          return dimBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public java.util.List<? extends com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.DimOrBuilder> 
           getDimOrBuilderList() {
        if (dimBuilder_ != null) {
          return dimBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dim_);
        }
      }
      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.Builder addDimBuilder() {
        return getDimFieldBuilder().addBuilder(
            com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.getDefaultInstance());
      }
      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.Builder addDimBuilder(
          int index) {
        return getDimFieldBuilder().addBuilder(
            index, com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.getDefaultInstance());
      }
      /**
       * <pre>
       * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
       * for a 30 x 40 2D tensor.  If an entry has size -1, this
       * corresponds to a dimension of unknown size. The names are
       * optional.
       * The order of entries in "dim" matters: It indicates the layout of the
       * values in the tensor in-memory representation.
       * The first entry in "dim" is the outermost dimension used to layout the
       * values, the last entry is the innermost dimension.  This matches the
       * in-memory layout of RowMajor Eigen tensors.
       * If "dim.size()" &gt; 0, "unknown_rank" must be false.
       * </pre>
       *
       * <code>repeated .angel.TensorShapeProto.Dim dim = 2;</code>
       */
      public java.util.List<com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.Builder> 
           getDimBuilderList() {
        return getDimFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim, com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.Builder, com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.DimOrBuilder> 
          getDimFieldBuilder() {
        if (dimBuilder_ == null) {
          dimBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim, com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.Dim.Builder, com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto.DimOrBuilder>(
                  dim_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          dim_ = null;
        }
        return dimBuilder_;
      }

      private boolean unknownRank_ ;
      /**
       * <pre>
       * If true, the number of dimensions in the shape is unknown.
       * If true, "dim.size()" must be 0.
       * </pre>
       *
       * <code>bool unknown_rank = 3;</code>
       */
      public boolean getUnknownRank() {
        return unknownRank_;
      }
      /**
       * <pre>
       * If true, the number of dimensions in the shape is unknown.
       * If true, "dim.size()" must be 0.
       * </pre>
       *
       * <code>bool unknown_rank = 3;</code>
       */
      public Builder setUnknownRank(boolean value) {
        
        unknownRank_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * If true, the number of dimensions in the shape is unknown.
       * If true, "dim.size()" must be 0.
       * </pre>
       *
       * <code>bool unknown_rank = 3;</code>
       */
      public Builder clearUnknownRank() {
        
        unknownRank_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:angel.TensorShapeProto)
    }

    // @@protoc_insertion_point(class_scope:angel.TensorShapeProto)
    private static final com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto();
    }

    public static com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TensorShapeProto>
        PARSER = new com.google.protobuf.AbstractParser<TensorShapeProto>() {
      public TensorShapeProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TensorShapeProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TensorShapeProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TensorShapeProto> getParserForType() {
      return PARSER;
    }

    public com.tencent.angel.core.graph.TensorShapeProtos.TensorShapeProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_angel_TensorShapeProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_angel_TensorShapeProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_angel_TensorShapeProto_Dim_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_angel_TensorShapeProto_Dim_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035core/graph/tensor_shape.proto\022\005angel\"u" +
      "\n\020TensorShapeProto\022(\n\003dim\030\002 \003(\0132\033.angel." +
      "TensorShapeProto.Dim\022\024\n\014unknown_rank\030\003 \001" +
      "(\010\032!\n\003Dim\022\014\n\004size\030\001 \001(\003\022\014\n\004name\030\002 \001(\tB3\n" +
      "\034com.tencent.angel.core.graphB\021TensorSha" +
      "peProtosP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_angel_TensorShapeProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_angel_TensorShapeProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_angel_TensorShapeProto_descriptor,
        new java.lang.String[] { "Dim", "UnknownRank", });
    internal_static_angel_TensorShapeProto_Dim_descriptor =
      internal_static_angel_TensorShapeProto_descriptor.getNestedTypes().get(0);
    internal_static_angel_TensorShapeProto_Dim_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_angel_TensorShapeProto_Dim_descriptor,
        new java.lang.String[] { "Size", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
