// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config/monitoring_config.proto

package com.tencent.angel.config;

public final class MonitoringConfigProtos {
  private MonitoringConfigProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PrometheusConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:angel.PrometheusConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Whether to expose Prometheus metrics.
     * </pre>
     *
     * <code>bool enable = 1;</code>
     */
    boolean getEnable();

    /**
     * <pre>
     * The endpoint to expose Prometheus metrics.
     * If not specified, PrometheusExporter::kPrometheusPath value is used.
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    java.lang.String getPath();
    /**
     * <pre>
     * The endpoint to expose Prometheus metrics.
     * If not specified, PrometheusExporter::kPrometheusPath value is used.
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    com.google.protobuf.ByteString
        getPathBytes();
  }
  /**
   * <pre>
   * Configuration for Prometheus monitoring.
   * </pre>
   *
   * Protobuf type {@code angel.PrometheusConfig}
   */
  public  static final class PrometheusConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:angel.PrometheusConfig)
      PrometheusConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PrometheusConfig.newBuilder() to construct.
    private PrometheusConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PrometheusConfig() {
      enable_ = false;
      path_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PrometheusConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              enable_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              path_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.angel.config.MonitoringConfigProtos.internal_static_angel_PrometheusConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.angel.config.MonitoringConfigProtos.internal_static_angel_PrometheusConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.class, com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.Builder.class);
    }

    public static final int ENABLE_FIELD_NUMBER = 1;
    private boolean enable_;
    /**
     * <pre>
     * Whether to expose Prometheus metrics.
     * </pre>
     *
     * <code>bool enable = 1;</code>
     */
    public boolean getEnable() {
      return enable_;
    }

    public static final int PATH_FIELD_NUMBER = 2;
    private volatile java.lang.Object path_;
    /**
     * <pre>
     * The endpoint to expose Prometheus metrics.
     * If not specified, PrometheusExporter::kPrometheusPath value is used.
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The endpoint to expose Prometheus metrics.
     * If not specified, PrometheusExporter::kPrometheusPath value is used.
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (enable_ != false) {
        output.writeBool(1, enable_);
      }
      if (!getPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, path_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (enable_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, enable_);
      }
      if (!getPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, path_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig)) {
        return super.equals(obj);
      }
      com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig other = (com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig) obj;

      boolean result = true;
      result = result && (getEnable()
          == other.getEnable());
      result = result && getPath()
          .equals(other.getPath());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEnable());
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Configuration for Prometheus monitoring.
     * </pre>
     *
     * Protobuf type {@code angel.PrometheusConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:angel.PrometheusConfig)
        com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.angel.config.MonitoringConfigProtos.internal_static_angel_PrometheusConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.angel.config.MonitoringConfigProtos.internal_static_angel_PrometheusConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.class, com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.Builder.class);
      }

      // Construct using com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        enable_ = false;

        path_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.angel.config.MonitoringConfigProtos.internal_static_angel_PrometheusConfig_descriptor;
      }

      public com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig getDefaultInstanceForType() {
        return com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.getDefaultInstance();
      }

      public com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig build() {
        com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig buildPartial() {
        com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig result = new com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig(this);
        result.enable_ = enable_;
        result.path_ = path_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig) {
          return mergeFrom((com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig other) {
        if (other == com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.getDefaultInstance()) return this;
        if (other.getEnable() != false) {
          setEnable(other.getEnable());
        }
        if (!other.getPath().isEmpty()) {
          path_ = other.path_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean enable_ ;
      /**
       * <pre>
       * Whether to expose Prometheus metrics.
       * </pre>
       *
       * <code>bool enable = 1;</code>
       */
      public boolean getEnable() {
        return enable_;
      }
      /**
       * <pre>
       * Whether to expose Prometheus metrics.
       * </pre>
       *
       * <code>bool enable = 1;</code>
       */
      public Builder setEnable(boolean value) {
        
        enable_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether to expose Prometheus metrics.
       * </pre>
       *
       * <code>bool enable = 1;</code>
       */
      public Builder clearEnable() {
        
        enable_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <pre>
       * The endpoint to expose Prometheus metrics.
       * If not specified, PrometheusExporter::kPrometheusPath value is used.
       * </pre>
       *
       * <code>string path = 2;</code>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The endpoint to expose Prometheus metrics.
       * If not specified, PrometheusExporter::kPrometheusPath value is used.
       * </pre>
       *
       * <code>string path = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The endpoint to expose Prometheus metrics.
       * If not specified, PrometheusExporter::kPrometheusPath value is used.
       * </pre>
       *
       * <code>string path = 2;</code>
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The endpoint to expose Prometheus metrics.
       * If not specified, PrometheusExporter::kPrometheusPath value is used.
       * </pre>
       *
       * <code>string path = 2;</code>
       */
      public Builder clearPath() {
        
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The endpoint to expose Prometheus metrics.
       * If not specified, PrometheusExporter::kPrometheusPath value is used.
       * </pre>
       *
       * <code>string path = 2;</code>
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        path_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:angel.PrometheusConfig)
    }

    // @@protoc_insertion_point(class_scope:angel.PrometheusConfig)
    private static final com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig();
    }

    public static com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PrometheusConfig>
        PARSER = new com.google.protobuf.AbstractParser<PrometheusConfig>() {
      public PrometheusConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PrometheusConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PrometheusConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PrometheusConfig> getParserForType() {
      return PARSER;
    }

    public com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MonitoringConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:angel.MonitoringConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.angel.PrometheusConfig prometheus_config = 1;</code>
     */
    boolean hasPrometheusConfig();
    /**
     * <code>.angel.PrometheusConfig prometheus_config = 1;</code>
     */
    com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig getPrometheusConfig();
    /**
     * <code>.angel.PrometheusConfig prometheus_config = 1;</code>
     */
    com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfigOrBuilder getPrometheusConfigOrBuilder();
  }
  /**
   * <pre>
   * Configuration for monitoring.
   * </pre>
   *
   * Protobuf type {@code angel.MonitoringConfig}
   */
  public  static final class MonitoringConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:angel.MonitoringConfig)
      MonitoringConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MonitoringConfig.newBuilder() to construct.
    private MonitoringConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MonitoringConfig() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MonitoringConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.Builder subBuilder = null;
              if (prometheusConfig_ != null) {
                subBuilder = prometheusConfig_.toBuilder();
              }
              prometheusConfig_ = input.readMessage(com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(prometheusConfig_);
                prometheusConfig_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.angel.config.MonitoringConfigProtos.internal_static_angel_MonitoringConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.angel.config.MonitoringConfigProtos.internal_static_angel_MonitoringConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig.class, com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig.Builder.class);
    }

    public static final int PROMETHEUS_CONFIG_FIELD_NUMBER = 1;
    private com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig prometheusConfig_;
    /**
     * <code>.angel.PrometheusConfig prometheus_config = 1;</code>
     */
    public boolean hasPrometheusConfig() {
      return prometheusConfig_ != null;
    }
    /**
     * <code>.angel.PrometheusConfig prometheus_config = 1;</code>
     */
    public com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig getPrometheusConfig() {
      return prometheusConfig_ == null ? com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.getDefaultInstance() : prometheusConfig_;
    }
    /**
     * <code>.angel.PrometheusConfig prometheus_config = 1;</code>
     */
    public com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfigOrBuilder getPrometheusConfigOrBuilder() {
      return getPrometheusConfig();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (prometheusConfig_ != null) {
        output.writeMessage(1, getPrometheusConfig());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (prometheusConfig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPrometheusConfig());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig)) {
        return super.equals(obj);
      }
      com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig other = (com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig) obj;

      boolean result = true;
      result = result && (hasPrometheusConfig() == other.hasPrometheusConfig());
      if (hasPrometheusConfig()) {
        result = result && getPrometheusConfig()
            .equals(other.getPrometheusConfig());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPrometheusConfig()) {
        hash = (37 * hash) + PROMETHEUS_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getPrometheusConfig().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Configuration for monitoring.
     * </pre>
     *
     * Protobuf type {@code angel.MonitoringConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:angel.MonitoringConfig)
        com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.angel.config.MonitoringConfigProtos.internal_static_angel_MonitoringConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.angel.config.MonitoringConfigProtos.internal_static_angel_MonitoringConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig.class, com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig.Builder.class);
      }

      // Construct using com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (prometheusConfigBuilder_ == null) {
          prometheusConfig_ = null;
        } else {
          prometheusConfig_ = null;
          prometheusConfigBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.angel.config.MonitoringConfigProtos.internal_static_angel_MonitoringConfig_descriptor;
      }

      public com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig getDefaultInstanceForType() {
        return com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig.getDefaultInstance();
      }

      public com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig build() {
        com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig buildPartial() {
        com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig result = new com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig(this);
        if (prometheusConfigBuilder_ == null) {
          result.prometheusConfig_ = prometheusConfig_;
        } else {
          result.prometheusConfig_ = prometheusConfigBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig) {
          return mergeFrom((com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig other) {
        if (other == com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig.getDefaultInstance()) return this;
        if (other.hasPrometheusConfig()) {
          mergePrometheusConfig(other.getPrometheusConfig());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig prometheusConfig_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig, com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.Builder, com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfigOrBuilder> prometheusConfigBuilder_;
      /**
       * <code>.angel.PrometheusConfig prometheus_config = 1;</code>
       */
      public boolean hasPrometheusConfig() {
        return prometheusConfigBuilder_ != null || prometheusConfig_ != null;
      }
      /**
       * <code>.angel.PrometheusConfig prometheus_config = 1;</code>
       */
      public com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig getPrometheusConfig() {
        if (prometheusConfigBuilder_ == null) {
          return prometheusConfig_ == null ? com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.getDefaultInstance() : prometheusConfig_;
        } else {
          return prometheusConfigBuilder_.getMessage();
        }
      }
      /**
       * <code>.angel.PrometheusConfig prometheus_config = 1;</code>
       */
      public Builder setPrometheusConfig(com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig value) {
        if (prometheusConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          prometheusConfig_ = value;
          onChanged();
        } else {
          prometheusConfigBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.angel.PrometheusConfig prometheus_config = 1;</code>
       */
      public Builder setPrometheusConfig(
          com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.Builder builderForValue) {
        if (prometheusConfigBuilder_ == null) {
          prometheusConfig_ = builderForValue.build();
          onChanged();
        } else {
          prometheusConfigBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.angel.PrometheusConfig prometheus_config = 1;</code>
       */
      public Builder mergePrometheusConfig(com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig value) {
        if (prometheusConfigBuilder_ == null) {
          if (prometheusConfig_ != null) {
            prometheusConfig_ =
              com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.newBuilder(prometheusConfig_).mergeFrom(value).buildPartial();
          } else {
            prometheusConfig_ = value;
          }
          onChanged();
        } else {
          prometheusConfigBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.angel.PrometheusConfig prometheus_config = 1;</code>
       */
      public Builder clearPrometheusConfig() {
        if (prometheusConfigBuilder_ == null) {
          prometheusConfig_ = null;
          onChanged();
        } else {
          prometheusConfig_ = null;
          prometheusConfigBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.angel.PrometheusConfig prometheus_config = 1;</code>
       */
      public com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.Builder getPrometheusConfigBuilder() {
        
        onChanged();
        return getPrometheusConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>.angel.PrometheusConfig prometheus_config = 1;</code>
       */
      public com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfigOrBuilder getPrometheusConfigOrBuilder() {
        if (prometheusConfigBuilder_ != null) {
          return prometheusConfigBuilder_.getMessageOrBuilder();
        } else {
          return prometheusConfig_ == null ?
              com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.getDefaultInstance() : prometheusConfig_;
        }
      }
      /**
       * <code>.angel.PrometheusConfig prometheus_config = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig, com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.Builder, com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfigOrBuilder> 
          getPrometheusConfigFieldBuilder() {
        if (prometheusConfigBuilder_ == null) {
          prometheusConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig, com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfig.Builder, com.tencent.angel.config.MonitoringConfigProtos.PrometheusConfigOrBuilder>(
                  getPrometheusConfig(),
                  getParentForChildren(),
                  isClean());
          prometheusConfig_ = null;
        }
        return prometheusConfigBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:angel.MonitoringConfig)
    }

    // @@protoc_insertion_point(class_scope:angel.MonitoringConfig)
    private static final com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig();
    }

    public static com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MonitoringConfig>
        PARSER = new com.google.protobuf.AbstractParser<MonitoringConfig>() {
      public MonitoringConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MonitoringConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MonitoringConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MonitoringConfig> getParserForType() {
      return PARSER;
    }

    public com.tencent.angel.config.MonitoringConfigProtos.MonitoringConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_angel_PrometheusConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_angel_PrometheusConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_angel_MonitoringConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_angel_MonitoringConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036config/monitoring_config.proto\022\005angel\"" +
      "0\n\020PrometheusConfig\022\016\n\006enable\030\001 \001(\010\022\014\n\004p" +
      "ath\030\002 \001(\t\"F\n\020MonitoringConfig\0222\n\021prometh" +
      "eus_config\030\001 \001(\0132\027.angel.PrometheusConfi" +
      "gB4\n\030com.tencent.angel.configB\026Monitorin" +
      "gConfigProtosP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_angel_PrometheusConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_angel_PrometheusConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_angel_PrometheusConfig_descriptor,
        new java.lang.String[] { "Enable", "Path", });
    internal_static_angel_MonitoringConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_angel_MonitoringConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_angel_MonitoringConfig_descriptor,
        new java.lang.String[] { "PrometheusConfig", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
