// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config/logging_config.proto

package com.tencent.angel.config;

public final class SamplingConfigProtos {
  private SamplingConfigProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SamplingConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:angel.SamplingConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Requests will be logged uniformly at random with this probability. Valid
     * range: [0, 1.0].
     * </pre>
     *
     * <code>double sampling_rate = 1;</code>
     */
    double getSamplingRate();
  }
  /**
   * Protobuf type {@code angel.SamplingConfig}
   */
  public  static final class SamplingConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:angel.SamplingConfig)
      SamplingConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SamplingConfig.newBuilder() to construct.
    private SamplingConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SamplingConfig() {
      samplingRate_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SamplingConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              samplingRate_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.angel.config.SamplingConfigProtos.internal_static_angel_SamplingConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.angel.config.SamplingConfigProtos.internal_static_angel_SamplingConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.class, com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.Builder.class);
    }

    public static final int SAMPLING_RATE_FIELD_NUMBER = 1;
    private double samplingRate_;
    /**
     * <pre>
     * Requests will be logged uniformly at random with this probability. Valid
     * range: [0, 1.0].
     * </pre>
     *
     * <code>double sampling_rate = 1;</code>
     */
    public double getSamplingRate() {
      return samplingRate_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (samplingRate_ != 0D) {
        output.writeDouble(1, samplingRate_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (samplingRate_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, samplingRate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.angel.config.SamplingConfigProtos.SamplingConfig)) {
        return super.equals(obj);
      }
      com.tencent.angel.config.SamplingConfigProtos.SamplingConfig other = (com.tencent.angel.config.SamplingConfigProtos.SamplingConfig) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getSamplingRate())
          == java.lang.Double.doubleToLongBits(
              other.getSamplingRate()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SAMPLING_RATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSamplingRate()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.angel.config.SamplingConfigProtos.SamplingConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.SamplingConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.SamplingConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.SamplingConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.SamplingConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.SamplingConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.SamplingConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.SamplingConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.SamplingConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.SamplingConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.SamplingConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.SamplingConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.angel.config.SamplingConfigProtos.SamplingConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code angel.SamplingConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:angel.SamplingConfig)
        com.tencent.angel.config.SamplingConfigProtos.SamplingConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.angel.config.SamplingConfigProtos.internal_static_angel_SamplingConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.angel.config.SamplingConfigProtos.internal_static_angel_SamplingConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.class, com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.Builder.class);
      }

      // Construct using com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        samplingRate_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.angel.config.SamplingConfigProtos.internal_static_angel_SamplingConfig_descriptor;
      }

      public com.tencent.angel.config.SamplingConfigProtos.SamplingConfig getDefaultInstanceForType() {
        return com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.getDefaultInstance();
      }

      public com.tencent.angel.config.SamplingConfigProtos.SamplingConfig build() {
        com.tencent.angel.config.SamplingConfigProtos.SamplingConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tencent.angel.config.SamplingConfigProtos.SamplingConfig buildPartial() {
        com.tencent.angel.config.SamplingConfigProtos.SamplingConfig result = new com.tencent.angel.config.SamplingConfigProtos.SamplingConfig(this);
        result.samplingRate_ = samplingRate_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.angel.config.SamplingConfigProtos.SamplingConfig) {
          return mergeFrom((com.tencent.angel.config.SamplingConfigProtos.SamplingConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.angel.config.SamplingConfigProtos.SamplingConfig other) {
        if (other == com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.getDefaultInstance()) return this;
        if (other.getSamplingRate() != 0D) {
          setSamplingRate(other.getSamplingRate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.angel.config.SamplingConfigProtos.SamplingConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.angel.config.SamplingConfigProtos.SamplingConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double samplingRate_ ;
      /**
       * <pre>
       * Requests will be logged uniformly at random with this probability. Valid
       * range: [0, 1.0].
       * </pre>
       *
       * <code>double sampling_rate = 1;</code>
       */
      public double getSamplingRate() {
        return samplingRate_;
      }
      /**
       * <pre>
       * Requests will be logged uniformly at random with this probability. Valid
       * range: [0, 1.0].
       * </pre>
       *
       * <code>double sampling_rate = 1;</code>
       */
      public Builder setSamplingRate(double value) {
        
        samplingRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Requests will be logged uniformly at random with this probability. Valid
       * range: [0, 1.0].
       * </pre>
       *
       * <code>double sampling_rate = 1;</code>
       */
      public Builder clearSamplingRate() {
        
        samplingRate_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:angel.SamplingConfig)
    }

    // @@protoc_insertion_point(class_scope:angel.SamplingConfig)
    private static final com.tencent.angel.config.SamplingConfigProtos.SamplingConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.angel.config.SamplingConfigProtos.SamplingConfig();
    }

    public static com.tencent.angel.config.SamplingConfigProtos.SamplingConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SamplingConfig>
        PARSER = new com.google.protobuf.AbstractParser<SamplingConfig>() {
      public SamplingConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SamplingConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SamplingConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SamplingConfig> getParserForType() {
      return PARSER;
    }

    public com.tencent.angel.config.SamplingConfigProtos.SamplingConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoggingConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:angel.LoggingConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.angel.LogCollectorConfig log_collector_config = 1;</code>
     */
    boolean hasLogCollectorConfig();
    /**
     * <code>.angel.LogCollectorConfig log_collector_config = 1;</code>
     */
    com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig getLogCollectorConfig();
    /**
     * <code>.angel.LogCollectorConfig log_collector_config = 1;</code>
     */
    com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfigOrBuilder getLogCollectorConfigOrBuilder();

    /**
     * <code>.angel.SamplingConfig sampling_config = 2;</code>
     */
    boolean hasSamplingConfig();
    /**
     * <code>.angel.SamplingConfig sampling_config = 2;</code>
     */
    com.tencent.angel.config.SamplingConfigProtos.SamplingConfig getSamplingConfig();
    /**
     * <code>.angel.SamplingConfig sampling_config = 2;</code>
     */
    com.tencent.angel.config.SamplingConfigProtos.SamplingConfigOrBuilder getSamplingConfigOrBuilder();
  }
  /**
   * <pre>
   * Configuration for logging query/responses.
   * </pre>
   *
   * Protobuf type {@code angel.LoggingConfig}
   */
  public  static final class LoggingConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:angel.LoggingConfig)
      LoggingConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoggingConfig.newBuilder() to construct.
    private LoggingConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoggingConfig() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoggingConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig.Builder subBuilder = null;
              if (logCollectorConfig_ != null) {
                subBuilder = logCollectorConfig_.toBuilder();
              }
              logCollectorConfig_ = input.readMessage(com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(logCollectorConfig_);
                logCollectorConfig_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.Builder subBuilder = null;
              if (samplingConfig_ != null) {
                subBuilder = samplingConfig_.toBuilder();
              }
              samplingConfig_ = input.readMessage(com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(samplingConfig_);
                samplingConfig_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.angel.config.SamplingConfigProtos.internal_static_angel_LoggingConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.angel.config.SamplingConfigProtos.internal_static_angel_LoggingConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.angel.config.SamplingConfigProtos.LoggingConfig.class, com.tencent.angel.config.SamplingConfigProtos.LoggingConfig.Builder.class);
    }

    public static final int LOG_COLLECTOR_CONFIG_FIELD_NUMBER = 1;
    private com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig logCollectorConfig_;
    /**
     * <code>.angel.LogCollectorConfig log_collector_config = 1;</code>
     */
    public boolean hasLogCollectorConfig() {
      return logCollectorConfig_ != null;
    }
    /**
     * <code>.angel.LogCollectorConfig log_collector_config = 1;</code>
     */
    public com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig getLogCollectorConfig() {
      return logCollectorConfig_ == null ? com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig.getDefaultInstance() : logCollectorConfig_;
    }
    /**
     * <code>.angel.LogCollectorConfig log_collector_config = 1;</code>
     */
    public com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfigOrBuilder getLogCollectorConfigOrBuilder() {
      return getLogCollectorConfig();
    }

    public static final int SAMPLING_CONFIG_FIELD_NUMBER = 2;
    private com.tencent.angel.config.SamplingConfigProtos.SamplingConfig samplingConfig_;
    /**
     * <code>.angel.SamplingConfig sampling_config = 2;</code>
     */
    public boolean hasSamplingConfig() {
      return samplingConfig_ != null;
    }
    /**
     * <code>.angel.SamplingConfig sampling_config = 2;</code>
     */
    public com.tencent.angel.config.SamplingConfigProtos.SamplingConfig getSamplingConfig() {
      return samplingConfig_ == null ? com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.getDefaultInstance() : samplingConfig_;
    }
    /**
     * <code>.angel.SamplingConfig sampling_config = 2;</code>
     */
    public com.tencent.angel.config.SamplingConfigProtos.SamplingConfigOrBuilder getSamplingConfigOrBuilder() {
      return getSamplingConfig();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (logCollectorConfig_ != null) {
        output.writeMessage(1, getLogCollectorConfig());
      }
      if (samplingConfig_ != null) {
        output.writeMessage(2, getSamplingConfig());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (logCollectorConfig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLogCollectorConfig());
      }
      if (samplingConfig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSamplingConfig());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.angel.config.SamplingConfigProtos.LoggingConfig)) {
        return super.equals(obj);
      }
      com.tencent.angel.config.SamplingConfigProtos.LoggingConfig other = (com.tencent.angel.config.SamplingConfigProtos.LoggingConfig) obj;

      boolean result = true;
      result = result && (hasLogCollectorConfig() == other.hasLogCollectorConfig());
      if (hasLogCollectorConfig()) {
        result = result && getLogCollectorConfig()
            .equals(other.getLogCollectorConfig());
      }
      result = result && (hasSamplingConfig() == other.hasSamplingConfig());
      if (hasSamplingConfig()) {
        result = result && getSamplingConfig()
            .equals(other.getSamplingConfig());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLogCollectorConfig()) {
        hash = (37 * hash) + LOG_COLLECTOR_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getLogCollectorConfig().hashCode();
      }
      if (hasSamplingConfig()) {
        hash = (37 * hash) + SAMPLING_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getSamplingConfig().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.angel.config.SamplingConfigProtos.LoggingConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.LoggingConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.LoggingConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.LoggingConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.LoggingConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.LoggingConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.LoggingConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.LoggingConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.LoggingConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.LoggingConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.LoggingConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.angel.config.SamplingConfigProtos.LoggingConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.angel.config.SamplingConfigProtos.LoggingConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Configuration for logging query/responses.
     * </pre>
     *
     * Protobuf type {@code angel.LoggingConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:angel.LoggingConfig)
        com.tencent.angel.config.SamplingConfigProtos.LoggingConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.angel.config.SamplingConfigProtos.internal_static_angel_LoggingConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.angel.config.SamplingConfigProtos.internal_static_angel_LoggingConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.angel.config.SamplingConfigProtos.LoggingConfig.class, com.tencent.angel.config.SamplingConfigProtos.LoggingConfig.Builder.class);
      }

      // Construct using com.tencent.angel.config.SamplingConfigProtos.LoggingConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (logCollectorConfigBuilder_ == null) {
          logCollectorConfig_ = null;
        } else {
          logCollectorConfig_ = null;
          logCollectorConfigBuilder_ = null;
        }
        if (samplingConfigBuilder_ == null) {
          samplingConfig_ = null;
        } else {
          samplingConfig_ = null;
          samplingConfigBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.angel.config.SamplingConfigProtos.internal_static_angel_LoggingConfig_descriptor;
      }

      public com.tencent.angel.config.SamplingConfigProtos.LoggingConfig getDefaultInstanceForType() {
        return com.tencent.angel.config.SamplingConfigProtos.LoggingConfig.getDefaultInstance();
      }

      public com.tencent.angel.config.SamplingConfigProtos.LoggingConfig build() {
        com.tencent.angel.config.SamplingConfigProtos.LoggingConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tencent.angel.config.SamplingConfigProtos.LoggingConfig buildPartial() {
        com.tencent.angel.config.SamplingConfigProtos.LoggingConfig result = new com.tencent.angel.config.SamplingConfigProtos.LoggingConfig(this);
        if (logCollectorConfigBuilder_ == null) {
          result.logCollectorConfig_ = logCollectorConfig_;
        } else {
          result.logCollectorConfig_ = logCollectorConfigBuilder_.build();
        }
        if (samplingConfigBuilder_ == null) {
          result.samplingConfig_ = samplingConfig_;
        } else {
          result.samplingConfig_ = samplingConfigBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.angel.config.SamplingConfigProtos.LoggingConfig) {
          return mergeFrom((com.tencent.angel.config.SamplingConfigProtos.LoggingConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.angel.config.SamplingConfigProtos.LoggingConfig other) {
        if (other == com.tencent.angel.config.SamplingConfigProtos.LoggingConfig.getDefaultInstance()) return this;
        if (other.hasLogCollectorConfig()) {
          mergeLogCollectorConfig(other.getLogCollectorConfig());
        }
        if (other.hasSamplingConfig()) {
          mergeSamplingConfig(other.getSamplingConfig());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.angel.config.SamplingConfigProtos.LoggingConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.angel.config.SamplingConfigProtos.LoggingConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig logCollectorConfig_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig, com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig.Builder, com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfigOrBuilder> logCollectorConfigBuilder_;
      /**
       * <code>.angel.LogCollectorConfig log_collector_config = 1;</code>
       */
      public boolean hasLogCollectorConfig() {
        return logCollectorConfigBuilder_ != null || logCollectorConfig_ != null;
      }
      /**
       * <code>.angel.LogCollectorConfig log_collector_config = 1;</code>
       */
      public com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig getLogCollectorConfig() {
        if (logCollectorConfigBuilder_ == null) {
          return logCollectorConfig_ == null ? com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig.getDefaultInstance() : logCollectorConfig_;
        } else {
          return logCollectorConfigBuilder_.getMessage();
        }
      }
      /**
       * <code>.angel.LogCollectorConfig log_collector_config = 1;</code>
       */
      public Builder setLogCollectorConfig(com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig value) {
        if (logCollectorConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          logCollectorConfig_ = value;
          onChanged();
        } else {
          logCollectorConfigBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.angel.LogCollectorConfig log_collector_config = 1;</code>
       */
      public Builder setLogCollectorConfig(
          com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig.Builder builderForValue) {
        if (logCollectorConfigBuilder_ == null) {
          logCollectorConfig_ = builderForValue.build();
          onChanged();
        } else {
          logCollectorConfigBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.angel.LogCollectorConfig log_collector_config = 1;</code>
       */
      public Builder mergeLogCollectorConfig(com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig value) {
        if (logCollectorConfigBuilder_ == null) {
          if (logCollectorConfig_ != null) {
            logCollectorConfig_ =
              com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig.newBuilder(logCollectorConfig_).mergeFrom(value).buildPartial();
          } else {
            logCollectorConfig_ = value;
          }
          onChanged();
        } else {
          logCollectorConfigBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.angel.LogCollectorConfig log_collector_config = 1;</code>
       */
      public Builder clearLogCollectorConfig() {
        if (logCollectorConfigBuilder_ == null) {
          logCollectorConfig_ = null;
          onChanged();
        } else {
          logCollectorConfig_ = null;
          logCollectorConfigBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.angel.LogCollectorConfig log_collector_config = 1;</code>
       */
      public com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig.Builder getLogCollectorConfigBuilder() {
        
        onChanged();
        return getLogCollectorConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>.angel.LogCollectorConfig log_collector_config = 1;</code>
       */
      public com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfigOrBuilder getLogCollectorConfigOrBuilder() {
        if (logCollectorConfigBuilder_ != null) {
          return logCollectorConfigBuilder_.getMessageOrBuilder();
        } else {
          return logCollectorConfig_ == null ?
              com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig.getDefaultInstance() : logCollectorConfig_;
        }
      }
      /**
       * <code>.angel.LogCollectorConfig log_collector_config = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig, com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig.Builder, com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfigOrBuilder> 
          getLogCollectorConfigFieldBuilder() {
        if (logCollectorConfigBuilder_ == null) {
          logCollectorConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig, com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfig.Builder, com.tencent.angel.config.LogCollectorConfigProtos.LogCollectorConfigOrBuilder>(
                  getLogCollectorConfig(),
                  getParentForChildren(),
                  isClean());
          logCollectorConfig_ = null;
        }
        return logCollectorConfigBuilder_;
      }

      private com.tencent.angel.config.SamplingConfigProtos.SamplingConfig samplingConfig_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.angel.config.SamplingConfigProtos.SamplingConfig, com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.Builder, com.tencent.angel.config.SamplingConfigProtos.SamplingConfigOrBuilder> samplingConfigBuilder_;
      /**
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      public boolean hasSamplingConfig() {
        return samplingConfigBuilder_ != null || samplingConfig_ != null;
      }
      /**
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      public com.tencent.angel.config.SamplingConfigProtos.SamplingConfig getSamplingConfig() {
        if (samplingConfigBuilder_ == null) {
          return samplingConfig_ == null ? com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.getDefaultInstance() : samplingConfig_;
        } else {
          return samplingConfigBuilder_.getMessage();
        }
      }
      /**
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      public Builder setSamplingConfig(com.tencent.angel.config.SamplingConfigProtos.SamplingConfig value) {
        if (samplingConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          samplingConfig_ = value;
          onChanged();
        } else {
          samplingConfigBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      public Builder setSamplingConfig(
          com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.Builder builderForValue) {
        if (samplingConfigBuilder_ == null) {
          samplingConfig_ = builderForValue.build();
          onChanged();
        } else {
          samplingConfigBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      public Builder mergeSamplingConfig(com.tencent.angel.config.SamplingConfigProtos.SamplingConfig value) {
        if (samplingConfigBuilder_ == null) {
          if (samplingConfig_ != null) {
            samplingConfig_ =
              com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.newBuilder(samplingConfig_).mergeFrom(value).buildPartial();
          } else {
            samplingConfig_ = value;
          }
          onChanged();
        } else {
          samplingConfigBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      public Builder clearSamplingConfig() {
        if (samplingConfigBuilder_ == null) {
          samplingConfig_ = null;
          onChanged();
        } else {
          samplingConfig_ = null;
          samplingConfigBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      public com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.Builder getSamplingConfigBuilder() {
        
        onChanged();
        return getSamplingConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      public com.tencent.angel.config.SamplingConfigProtos.SamplingConfigOrBuilder getSamplingConfigOrBuilder() {
        if (samplingConfigBuilder_ != null) {
          return samplingConfigBuilder_.getMessageOrBuilder();
        } else {
          return samplingConfig_ == null ?
              com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.getDefaultInstance() : samplingConfig_;
        }
      }
      /**
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.angel.config.SamplingConfigProtos.SamplingConfig, com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.Builder, com.tencent.angel.config.SamplingConfigProtos.SamplingConfigOrBuilder> 
          getSamplingConfigFieldBuilder() {
        if (samplingConfigBuilder_ == null) {
          samplingConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tencent.angel.config.SamplingConfigProtos.SamplingConfig, com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.Builder, com.tencent.angel.config.SamplingConfigProtos.SamplingConfigOrBuilder>(
                  getSamplingConfig(),
                  getParentForChildren(),
                  isClean());
          samplingConfig_ = null;
        }
        return samplingConfigBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:angel.LoggingConfig)
    }

    // @@protoc_insertion_point(class_scope:angel.LoggingConfig)
    private static final com.tencent.angel.config.SamplingConfigProtos.LoggingConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.angel.config.SamplingConfigProtos.LoggingConfig();
    }

    public static com.tencent.angel.config.SamplingConfigProtos.LoggingConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoggingConfig>
        PARSER = new com.google.protobuf.AbstractParser<LoggingConfig>() {
      public LoggingConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoggingConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoggingConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoggingConfig> getParserForType() {
      return PARSER;
    }

    public com.tencent.angel.config.SamplingConfigProtos.LoggingConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_angel_SamplingConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_angel_SamplingConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_angel_LoggingConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_angel_LoggingConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033config/logging_config.proto\022\005angel\032!co" +
      "nfig/log_collector_config.proto\"\'\n\016Sampl" +
      "ingConfig\022\025\n\rsampling_rate\030\001 \001(\001\"x\n\rLogg" +
      "ingConfig\0227\n\024log_collector_config\030\001 \001(\0132" +
      "\031.angel.LogCollectorConfig\022.\n\017sampling_c" +
      "onfig\030\002 \001(\0132\025.angel.SamplingConfigB2\n\030co" +
      "m.tencent.angel.configB\024SamplingConfigPr" +
      "otosP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tencent.angel.config.LogCollectorConfigProtos.getDescriptor(),
        }, assigner);
    internal_static_angel_SamplingConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_angel_SamplingConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_angel_SamplingConfig_descriptor,
        new java.lang.String[] { "SamplingRate", });
    internal_static_angel_LoggingConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_angel_LoggingConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_angel_LoggingConfig_descriptor,
        new java.lang.String[] { "LogCollectorConfig", "SamplingConfig", });
    com.tencent.angel.config.LogCollectorConfigProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
