/*
 * Tencent is pleased to support the open source community by making Angel available.
 *
 * Copyright (C) 2017-2018 THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 *
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apis/modelmgr/model_service.proto

package com.tencent.angel.serving.apis.modelmgr;

public final class ModelServiceProtos {
  private ModelServiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!apis/modelmgr/model_service.proto\022\rang" +
      "el.serving\032$apis/modelmgr/get_model_stat" +
      "us.proto\032$apis/modelmgr/model_management" +
      ".proto2\323\001\n\014ModelService\022]\n\016GetModelStatu" +
      "s\022$.angel.serving.GetModelStatusRequest\032" +
      "%.angel.serving.GetModelStatusResponse\022d" +
      "\n\031HandleReloadConfigRequest\022\".angel.serv" +
      "ing.ReloadConfigRequest\032#.angel.serving." +
      "ReloadConfigResponseB?\n\'com.tencent.ange" +
      "l.serving.apis.modelmgrB\022ModelServicePro" +
      "tosP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tencent.angel.serving.apis.modelmgr.GetModelStatusProtos.getDescriptor(),
          com.tencent.angel.serving.apis.modelmgr.ModelManagement.getDescriptor(),
        }, assigner);
    com.tencent.angel.serving.apis.modelmgr.GetModelStatusProtos.getDescriptor();
    com.tencent.angel.serving.apis.modelmgr.ModelManagement.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
