/*
 * Tencent is pleased to support the open source community by making Angel available.
 *
 * Copyright (C) 2017-2018 THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 *
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/logging.proto

package com.tencent.angel.core;

public final class LoggingProtos {
  private LoggingProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LogMetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:angel.LogMetadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.angel.serving.ModelSpec model_spec = 1;</code>
     */
    boolean hasModelSpec();
    /**
     * <code>.angel.serving.ModelSpec model_spec = 1;</code>
     */
    com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec getModelSpec();
    /**
     * <code>.angel.serving.ModelSpec model_spec = 1;</code>
     */
    com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpecOrBuilder getModelSpecOrBuilder();

    /**
     * <pre>
     * TODO(b/33279154): Add more metadata as mentioned in the bug.
     * </pre>
     *
     * <code>.angel.SamplingConfig sampling_config = 2;</code>
     */
    boolean hasSamplingConfig();
    /**
     * <pre>
     * TODO(b/33279154): Add more metadata as mentioned in the bug.
     * </pre>
     *
     * <code>.angel.SamplingConfig sampling_config = 2;</code>
     */
    com.tencent.angel.config.SamplingConfigProtos.SamplingConfig getSamplingConfig();
    /**
     * <pre>
     * TODO(b/33279154): Add more metadata as mentioned in the bug.
     * </pre>
     *
     * <code>.angel.SamplingConfig sampling_config = 2;</code>
     */
    com.tencent.angel.config.SamplingConfigProtos.SamplingConfigOrBuilder getSamplingConfigOrBuilder();
  }
  /**
   * <pre>
   * Metadata logged along with the request logs.
   * </pre>
   *
   * Protobuf type {@code angel.LogMetadata}
   */
  public  static final class LogMetadata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:angel.LogMetadata)
      LogMetadataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogMetadata.newBuilder() to construct.
    private LogMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogMetadata() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LogMetadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec.Builder subBuilder = null;
              if (modelSpec_ != null) {
                subBuilder = modelSpec_.toBuilder();
              }
              modelSpec_ = input.readMessage(com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(modelSpec_);
                modelSpec_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.Builder subBuilder = null;
              if (samplingConfig_ != null) {
                subBuilder = samplingConfig_.toBuilder();
              }
              samplingConfig_ = input.readMessage(com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(samplingConfig_);
                samplingConfig_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.angel.core.LoggingProtos.internal_static_angel_LogMetadata_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.angel.core.LoggingProtos.internal_static_angel_LogMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.angel.core.LoggingProtos.LogMetadata.class, com.tencent.angel.core.LoggingProtos.LogMetadata.Builder.class);
    }

    public static final int MODEL_SPEC_FIELD_NUMBER = 1;
    private com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec modelSpec_;
    /**
     * <code>.angel.serving.ModelSpec model_spec = 1;</code>
     */
    public boolean hasModelSpec() {
      return modelSpec_ != null;
    }
    /**
     * <code>.angel.serving.ModelSpec model_spec = 1;</code>
     */
    public com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec getModelSpec() {
      return modelSpec_ == null ? com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec.getDefaultInstance() : modelSpec_;
    }
    /**
     * <code>.angel.serving.ModelSpec model_spec = 1;</code>
     */
    public com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpecOrBuilder getModelSpecOrBuilder() {
      return getModelSpec();
    }

    public static final int SAMPLING_CONFIG_FIELD_NUMBER = 2;
    private com.tencent.angel.config.SamplingConfigProtos.SamplingConfig samplingConfig_;
    /**
     * <pre>
     * TODO(b/33279154): Add more metadata as mentioned in the bug.
     * </pre>
     *
     * <code>.angel.SamplingConfig sampling_config = 2;</code>
     */
    public boolean hasSamplingConfig() {
      return samplingConfig_ != null;
    }
    /**
     * <pre>
     * TODO(b/33279154): Add more metadata as mentioned in the bug.
     * </pre>
     *
     * <code>.angel.SamplingConfig sampling_config = 2;</code>
     */
    public com.tencent.angel.config.SamplingConfigProtos.SamplingConfig getSamplingConfig() {
      return samplingConfig_ == null ? com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.getDefaultInstance() : samplingConfig_;
    }
    /**
     * <pre>
     * TODO(b/33279154): Add more metadata as mentioned in the bug.
     * </pre>
     *
     * <code>.angel.SamplingConfig sampling_config = 2;</code>
     */
    public com.tencent.angel.config.SamplingConfigProtos.SamplingConfigOrBuilder getSamplingConfigOrBuilder() {
      return getSamplingConfig();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (modelSpec_ != null) {
        output.writeMessage(1, getModelSpec());
      }
      if (samplingConfig_ != null) {
        output.writeMessage(2, getSamplingConfig());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (modelSpec_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getModelSpec());
      }
      if (samplingConfig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSamplingConfig());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.angel.core.LoggingProtos.LogMetadata)) {
        return super.equals(obj);
      }
      com.tencent.angel.core.LoggingProtos.LogMetadata other = (com.tencent.angel.core.LoggingProtos.LogMetadata) obj;

      boolean result = true;
      result = result && (hasModelSpec() == other.hasModelSpec());
      if (hasModelSpec()) {
        result = result && getModelSpec()
            .equals(other.getModelSpec());
      }
      result = result && (hasSamplingConfig() == other.hasSamplingConfig());
      if (hasSamplingConfig()) {
        result = result && getSamplingConfig()
            .equals(other.getSamplingConfig());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasModelSpec()) {
        hash = (37 * hash) + MODEL_SPEC_FIELD_NUMBER;
        hash = (53 * hash) + getModelSpec().hashCode();
      }
      if (hasSamplingConfig()) {
        hash = (37 * hash) + SAMPLING_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getSamplingConfig().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.angel.core.LoggingProtos.LogMetadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.core.LoggingProtos.LogMetadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.core.LoggingProtos.LogMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.core.LoggingProtos.LogMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.core.LoggingProtos.LogMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.core.LoggingProtos.LogMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.core.LoggingProtos.LogMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.angel.core.LoggingProtos.LogMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.angel.core.LoggingProtos.LogMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.angel.core.LoggingProtos.LogMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.angel.core.LoggingProtos.LogMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.angel.core.LoggingProtos.LogMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.angel.core.LoggingProtos.LogMetadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Metadata logged along with the request logs.
     * </pre>
     *
     * Protobuf type {@code angel.LogMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:angel.LogMetadata)
        com.tencent.angel.core.LoggingProtos.LogMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.angel.core.LoggingProtos.internal_static_angel_LogMetadata_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.angel.core.LoggingProtos.internal_static_angel_LogMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.angel.core.LoggingProtos.LogMetadata.class, com.tencent.angel.core.LoggingProtos.LogMetadata.Builder.class);
      }

      // Construct using com.tencent.angel.core.LoggingProtos.LogMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (modelSpecBuilder_ == null) {
          modelSpec_ = null;
        } else {
          modelSpec_ = null;
          modelSpecBuilder_ = null;
        }
        if (samplingConfigBuilder_ == null) {
          samplingConfig_ = null;
        } else {
          samplingConfig_ = null;
          samplingConfigBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.angel.core.LoggingProtos.internal_static_angel_LogMetadata_descriptor;
      }

      public com.tencent.angel.core.LoggingProtos.LogMetadata getDefaultInstanceForType() {
        return com.tencent.angel.core.LoggingProtos.LogMetadata.getDefaultInstance();
      }

      public com.tencent.angel.core.LoggingProtos.LogMetadata build() {
        com.tencent.angel.core.LoggingProtos.LogMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tencent.angel.core.LoggingProtos.LogMetadata buildPartial() {
        com.tencent.angel.core.LoggingProtos.LogMetadata result = new com.tencent.angel.core.LoggingProtos.LogMetadata(this);
        if (modelSpecBuilder_ == null) {
          result.modelSpec_ = modelSpec_;
        } else {
          result.modelSpec_ = modelSpecBuilder_.build();
        }
        if (samplingConfigBuilder_ == null) {
          result.samplingConfig_ = samplingConfig_;
        } else {
          result.samplingConfig_ = samplingConfigBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.angel.core.LoggingProtos.LogMetadata) {
          return mergeFrom((com.tencent.angel.core.LoggingProtos.LogMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.angel.core.LoggingProtos.LogMetadata other) {
        if (other == com.tencent.angel.core.LoggingProtos.LogMetadata.getDefaultInstance()) return this;
        if (other.hasModelSpec()) {
          mergeModelSpec(other.getModelSpec());
        }
        if (other.hasSamplingConfig()) {
          mergeSamplingConfig(other.getSamplingConfig());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.angel.core.LoggingProtos.LogMetadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.angel.core.LoggingProtos.LogMetadata) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec modelSpec_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec, com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec.Builder, com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpecOrBuilder> modelSpecBuilder_;
      /**
       * <code>.angel.serving.ModelSpec model_spec = 1;</code>
       */
      public boolean hasModelSpec() {
        return modelSpecBuilder_ != null || modelSpec_ != null;
      }
      /**
       * <code>.angel.serving.ModelSpec model_spec = 1;</code>
       */
      public com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec getModelSpec() {
        if (modelSpecBuilder_ == null) {
          return modelSpec_ == null ? com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec.getDefaultInstance() : modelSpec_;
        } else {
          return modelSpecBuilder_.getMessage();
        }
      }
      /**
       * <code>.angel.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder setModelSpec(com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec value) {
        if (modelSpecBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          modelSpec_ = value;
          onChanged();
        } else {
          modelSpecBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.angel.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder setModelSpec(
          com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec.Builder builderForValue) {
        if (modelSpecBuilder_ == null) {
          modelSpec_ = builderForValue.build();
          onChanged();
        } else {
          modelSpecBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.angel.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder mergeModelSpec(com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec value) {
        if (modelSpecBuilder_ == null) {
          if (modelSpec_ != null) {
            modelSpec_ =
              com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec.newBuilder(modelSpec_).mergeFrom(value).buildPartial();
          } else {
            modelSpec_ = value;
          }
          onChanged();
        } else {
          modelSpecBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.angel.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder clearModelSpec() {
        if (modelSpecBuilder_ == null) {
          modelSpec_ = null;
          onChanged();
        } else {
          modelSpec_ = null;
          modelSpecBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.angel.serving.ModelSpec model_spec = 1;</code>
       */
      public com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec.Builder getModelSpecBuilder() {
        
        onChanged();
        return getModelSpecFieldBuilder().getBuilder();
      }
      /**
       * <code>.angel.serving.ModelSpec model_spec = 1;</code>
       */
      public com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpecOrBuilder getModelSpecOrBuilder() {
        if (modelSpecBuilder_ != null) {
          return modelSpecBuilder_.getMessageOrBuilder();
        } else {
          return modelSpec_ == null ?
              com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec.getDefaultInstance() : modelSpec_;
        }
      }
      /**
       * <code>.angel.serving.ModelSpec model_spec = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec, com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec.Builder, com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpecOrBuilder> 
          getModelSpecFieldBuilder() {
        if (modelSpecBuilder_ == null) {
          modelSpecBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec, com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpec.Builder, com.tencent.angel.serving.apis.common.ModelSpecProtos.ModelSpecOrBuilder>(
                  getModelSpec(),
                  getParentForChildren(),
                  isClean());
          modelSpec_ = null;
        }
        return modelSpecBuilder_;
      }

      private com.tencent.angel.config.SamplingConfigProtos.SamplingConfig samplingConfig_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.angel.config.SamplingConfigProtos.SamplingConfig, com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.Builder, com.tencent.angel.config.SamplingConfigProtos.SamplingConfigOrBuilder> samplingConfigBuilder_;
      /**
       * <pre>
       * TODO(b/33279154): Add more metadata as mentioned in the bug.
       * </pre>
       *
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      public boolean hasSamplingConfig() {
        return samplingConfigBuilder_ != null || samplingConfig_ != null;
      }
      /**
       * <pre>
       * TODO(b/33279154): Add more metadata as mentioned in the bug.
       * </pre>
       *
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      public com.tencent.angel.config.SamplingConfigProtos.SamplingConfig getSamplingConfig() {
        if (samplingConfigBuilder_ == null) {
          return samplingConfig_ == null ? com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.getDefaultInstance() : samplingConfig_;
        } else {
          return samplingConfigBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * TODO(b/33279154): Add more metadata as mentioned in the bug.
       * </pre>
       *
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      public Builder setSamplingConfig(com.tencent.angel.config.SamplingConfigProtos.SamplingConfig value) {
        if (samplingConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          samplingConfig_ = value;
          onChanged();
        } else {
          samplingConfigBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * TODO(b/33279154): Add more metadata as mentioned in the bug.
       * </pre>
       *
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      public Builder setSamplingConfig(
          com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.Builder builderForValue) {
        if (samplingConfigBuilder_ == null) {
          samplingConfig_ = builderForValue.build();
          onChanged();
        } else {
          samplingConfigBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * TODO(b/33279154): Add more metadata as mentioned in the bug.
       * </pre>
       *
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      public Builder mergeSamplingConfig(com.tencent.angel.config.SamplingConfigProtos.SamplingConfig value) {
        if (samplingConfigBuilder_ == null) {
          if (samplingConfig_ != null) {
            samplingConfig_ =
              com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.newBuilder(samplingConfig_).mergeFrom(value).buildPartial();
          } else {
            samplingConfig_ = value;
          }
          onChanged();
        } else {
          samplingConfigBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * TODO(b/33279154): Add more metadata as mentioned in the bug.
       * </pre>
       *
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      public Builder clearSamplingConfig() {
        if (samplingConfigBuilder_ == null) {
          samplingConfig_ = null;
          onChanged();
        } else {
          samplingConfig_ = null;
          samplingConfigBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * TODO(b/33279154): Add more metadata as mentioned in the bug.
       * </pre>
       *
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      public com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.Builder getSamplingConfigBuilder() {
        
        onChanged();
        return getSamplingConfigFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * TODO(b/33279154): Add more metadata as mentioned in the bug.
       * </pre>
       *
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      public com.tencent.angel.config.SamplingConfigProtos.SamplingConfigOrBuilder getSamplingConfigOrBuilder() {
        if (samplingConfigBuilder_ != null) {
          return samplingConfigBuilder_.getMessageOrBuilder();
        } else {
          return samplingConfig_ == null ?
              com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.getDefaultInstance() : samplingConfig_;
        }
      }
      /**
       * <pre>
       * TODO(b/33279154): Add more metadata as mentioned in the bug.
       * </pre>
       *
       * <code>.angel.SamplingConfig sampling_config = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.angel.config.SamplingConfigProtos.SamplingConfig, com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.Builder, com.tencent.angel.config.SamplingConfigProtos.SamplingConfigOrBuilder> 
          getSamplingConfigFieldBuilder() {
        if (samplingConfigBuilder_ == null) {
          samplingConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tencent.angel.config.SamplingConfigProtos.SamplingConfig, com.tencent.angel.config.SamplingConfigProtos.SamplingConfig.Builder, com.tencent.angel.config.SamplingConfigProtos.SamplingConfigOrBuilder>(
                  getSamplingConfig(),
                  getParentForChildren(),
                  isClean());
          samplingConfig_ = null;
        }
        return samplingConfigBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:angel.LogMetadata)
    }

    // @@protoc_insertion_point(class_scope:angel.LogMetadata)
    private static final com.tencent.angel.core.LoggingProtos.LogMetadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.angel.core.LoggingProtos.LogMetadata();
    }

    public static com.tencent.angel.core.LoggingProtos.LogMetadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogMetadata>
        PARSER = new com.google.protobuf.AbstractParser<LogMetadata>() {
      public LogMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogMetadata(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogMetadata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogMetadata> getParserForType() {
      return PARSER;
    }

    public com.tencent.angel.core.LoggingProtos.LogMetadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_angel_LogMetadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_angel_LogMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022core/logging.proto\022\005angel\032\027apis/common" +
      "/model.proto\032\033config/logging_config.prot" +
      "o\"k\n\013LogMetadata\022,\n\nmodel_spec\030\001 \001(\0132\030.a" +
      "ngel.serving.ModelSpec\022.\n\017sampling_confi" +
      "g\030\002 \001(\0132\025.angel.SamplingConfigB)\n\026com.te" +
      "ncent.angel.coreB\rLoggingProtosP\000b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tencent.angel.serving.apis.common.ModelSpecProtos.getDescriptor(),
          com.tencent.angel.config.SamplingConfigProtos.getDescriptor(),
        }, assigner);
    internal_static_angel_LogMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_angel_LogMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_angel_LogMetadata_descriptor,
        new java.lang.String[] { "ModelSpec", "SamplingConfig", });
    com.tencent.angel.serving.apis.common.ModelSpecProtos.getDescriptor();
    com.tencent.angel.config.SamplingConfigProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
