// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/saver/saved_model.proto

package com.tencent.angel.core.saver;

public final class SavedModelProtos {
  private SavedModelProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SavedModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:angel.SavedModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The schema version of the SavedModel instance. Used for versioning when
     * making future changes to the specification/implementation. Initial value
     * at release will be 1.
     * </pre>
     *
     * <code>int64 saved_model_schema_version = 1;</code>
     */
    long getSavedModelSchemaVersion();

    /**
     * <pre>
     * One or more MetaGraphs.
     * </pre>
     *
     * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
     */
    java.util.List<com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef> 
        getMetaGraphsList();
    /**
     * <pre>
     * One or more MetaGraphs.
     * </pre>
     *
     * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
     */
    com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef getMetaGraphs(int index);
    /**
     * <pre>
     * One or more MetaGraphs.
     * </pre>
     *
     * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
     */
    int getMetaGraphsCount();
    /**
     * <pre>
     * One or more MetaGraphs.
     * </pre>
     *
     * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
     */
    java.util.List<? extends com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDefOrBuilder> 
        getMetaGraphsOrBuilderList();
    /**
     * <pre>
     * One or more MetaGraphs.
     * </pre>
     *
     * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
     */
    com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDefOrBuilder getMetaGraphsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * SavedModel is the high level serialization format for TensorFlow Models.
   * See [todo: doc links, similar to session_bundle] for more information.
   * </pre>
   *
   * Protobuf type {@code angel.SavedModel}
   */
  public  static final class SavedModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:angel.SavedModel)
      SavedModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SavedModel.newBuilder() to construct.
    private SavedModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SavedModel() {
      savedModelSchemaVersion_ = 0L;
      metaGraphs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SavedModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              savedModelSchemaVersion_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                metaGraphs_ = new java.util.ArrayList<com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef>();
                mutable_bitField0_ |= 0x00000002;
              }
              metaGraphs_.add(
                  input.readMessage(com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          metaGraphs_ = java.util.Collections.unmodifiableList(metaGraphs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.angel.core.saver.SavedModelProtos.internal_static_angel_SavedModel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.angel.core.saver.SavedModelProtos.internal_static_angel_SavedModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.angel.core.saver.SavedModelProtos.SavedModel.class, com.tencent.angel.core.saver.SavedModelProtos.SavedModel.Builder.class);
    }

    private int bitField0_;
    public static final int SAVED_MODEL_SCHEMA_VERSION_FIELD_NUMBER = 1;
    private long savedModelSchemaVersion_;
    /**
     * <pre>
     * The schema version of the SavedModel instance. Used for versioning when
     * making future changes to the specification/implementation. Initial value
     * at release will be 1.
     * </pre>
     *
     * <code>int64 saved_model_schema_version = 1;</code>
     */
    public long getSavedModelSchemaVersion() {
      return savedModelSchemaVersion_;
    }

    public static final int META_GRAPHS_FIELD_NUMBER = 2;
    private java.util.List<com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef> metaGraphs_;
    /**
     * <pre>
     * One or more MetaGraphs.
     * </pre>
     *
     * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
     */
    public java.util.List<com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef> getMetaGraphsList() {
      return metaGraphs_;
    }
    /**
     * <pre>
     * One or more MetaGraphs.
     * </pre>
     *
     * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
     */
    public java.util.List<? extends com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDefOrBuilder> 
        getMetaGraphsOrBuilderList() {
      return metaGraphs_;
    }
    /**
     * <pre>
     * One or more MetaGraphs.
     * </pre>
     *
     * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
     */
    public int getMetaGraphsCount() {
      return metaGraphs_.size();
    }
    /**
     * <pre>
     * One or more MetaGraphs.
     * </pre>
     *
     * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
     */
    public com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef getMetaGraphs(int index) {
      return metaGraphs_.get(index);
    }
    /**
     * <pre>
     * One or more MetaGraphs.
     * </pre>
     *
     * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
     */
    public com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDefOrBuilder getMetaGraphsOrBuilder(
        int index) {
      return metaGraphs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (savedModelSchemaVersion_ != 0L) {
        output.writeInt64(1, savedModelSchemaVersion_);
      }
      for (int i = 0; i < metaGraphs_.size(); i++) {
        output.writeMessage(2, metaGraphs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (savedModelSchemaVersion_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, savedModelSchemaVersion_);
      }
      for (int i = 0; i < metaGraphs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, metaGraphs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.angel.core.saver.SavedModelProtos.SavedModel)) {
        return super.equals(obj);
      }
      com.tencent.angel.core.saver.SavedModelProtos.SavedModel other = (com.tencent.angel.core.saver.SavedModelProtos.SavedModel) obj;

      boolean result = true;
      result = result && (getSavedModelSchemaVersion()
          == other.getSavedModelSchemaVersion());
      result = result && getMetaGraphsList()
          .equals(other.getMetaGraphsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SAVED_MODEL_SCHEMA_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSavedModelSchemaVersion());
      if (getMetaGraphsCount() > 0) {
        hash = (37 * hash) + META_GRAPHS_FIELD_NUMBER;
        hash = (53 * hash) + getMetaGraphsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.angel.core.saver.SavedModelProtos.SavedModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.core.saver.SavedModelProtos.SavedModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.core.saver.SavedModelProtos.SavedModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.core.saver.SavedModelProtos.SavedModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.core.saver.SavedModelProtos.SavedModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.core.saver.SavedModelProtos.SavedModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.core.saver.SavedModelProtos.SavedModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.angel.core.saver.SavedModelProtos.SavedModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.angel.core.saver.SavedModelProtos.SavedModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.angel.core.saver.SavedModelProtos.SavedModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.angel.core.saver.SavedModelProtos.SavedModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.angel.core.saver.SavedModelProtos.SavedModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.angel.core.saver.SavedModelProtos.SavedModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * SavedModel is the high level serialization format for TensorFlow Models.
     * See [todo: doc links, similar to session_bundle] for more information.
     * </pre>
     *
     * Protobuf type {@code angel.SavedModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:angel.SavedModel)
        com.tencent.angel.core.saver.SavedModelProtos.SavedModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.angel.core.saver.SavedModelProtos.internal_static_angel_SavedModel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.angel.core.saver.SavedModelProtos.internal_static_angel_SavedModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.angel.core.saver.SavedModelProtos.SavedModel.class, com.tencent.angel.core.saver.SavedModelProtos.SavedModel.Builder.class);
      }

      // Construct using com.tencent.angel.core.saver.SavedModelProtos.SavedModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMetaGraphsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        savedModelSchemaVersion_ = 0L;

        if (metaGraphsBuilder_ == null) {
          metaGraphs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          metaGraphsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.angel.core.saver.SavedModelProtos.internal_static_angel_SavedModel_descriptor;
      }

      public com.tencent.angel.core.saver.SavedModelProtos.SavedModel getDefaultInstanceForType() {
        return com.tencent.angel.core.saver.SavedModelProtos.SavedModel.getDefaultInstance();
      }

      public com.tencent.angel.core.saver.SavedModelProtos.SavedModel build() {
        com.tencent.angel.core.saver.SavedModelProtos.SavedModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tencent.angel.core.saver.SavedModelProtos.SavedModel buildPartial() {
        com.tencent.angel.core.saver.SavedModelProtos.SavedModel result = new com.tencent.angel.core.saver.SavedModelProtos.SavedModel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.savedModelSchemaVersion_ = savedModelSchemaVersion_;
        if (metaGraphsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            metaGraphs_ = java.util.Collections.unmodifiableList(metaGraphs_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.metaGraphs_ = metaGraphs_;
        } else {
          result.metaGraphs_ = metaGraphsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.angel.core.saver.SavedModelProtos.SavedModel) {
          return mergeFrom((com.tencent.angel.core.saver.SavedModelProtos.SavedModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.angel.core.saver.SavedModelProtos.SavedModel other) {
        if (other == com.tencent.angel.core.saver.SavedModelProtos.SavedModel.getDefaultInstance()) return this;
        if (other.getSavedModelSchemaVersion() != 0L) {
          setSavedModelSchemaVersion(other.getSavedModelSchemaVersion());
        }
        if (metaGraphsBuilder_ == null) {
          if (!other.metaGraphs_.isEmpty()) {
            if (metaGraphs_.isEmpty()) {
              metaGraphs_ = other.metaGraphs_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMetaGraphsIsMutable();
              metaGraphs_.addAll(other.metaGraphs_);
            }
            onChanged();
          }
        } else {
          if (!other.metaGraphs_.isEmpty()) {
            if (metaGraphsBuilder_.isEmpty()) {
              metaGraphsBuilder_.dispose();
              metaGraphsBuilder_ = null;
              metaGraphs_ = other.metaGraphs_;
              bitField0_ = (bitField0_ & ~0x00000002);
              metaGraphsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMetaGraphsFieldBuilder() : null;
            } else {
              metaGraphsBuilder_.addAllMessages(other.metaGraphs_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.angel.core.saver.SavedModelProtos.SavedModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.angel.core.saver.SavedModelProtos.SavedModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long savedModelSchemaVersion_ ;
      /**
       * <pre>
       * The schema version of the SavedModel instance. Used for versioning when
       * making future changes to the specification/implementation. Initial value
       * at release will be 1.
       * </pre>
       *
       * <code>int64 saved_model_schema_version = 1;</code>
       */
      public long getSavedModelSchemaVersion() {
        return savedModelSchemaVersion_;
      }
      /**
       * <pre>
       * The schema version of the SavedModel instance. Used for versioning when
       * making future changes to the specification/implementation. Initial value
       * at release will be 1.
       * </pre>
       *
       * <code>int64 saved_model_schema_version = 1;</code>
       */
      public Builder setSavedModelSchemaVersion(long value) {
        
        savedModelSchemaVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The schema version of the SavedModel instance. Used for versioning when
       * making future changes to the specification/implementation. Initial value
       * at release will be 1.
       * </pre>
       *
       * <code>int64 saved_model_schema_version = 1;</code>
       */
      public Builder clearSavedModelSchemaVersion() {
        
        savedModelSchemaVersion_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef> metaGraphs_ =
        java.util.Collections.emptyList();
      private void ensureMetaGraphsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          metaGraphs_ = new java.util.ArrayList<com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef>(metaGraphs_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef, com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef.Builder, com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDefOrBuilder> metaGraphsBuilder_;

      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public java.util.List<com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef> getMetaGraphsList() {
        if (metaGraphsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(metaGraphs_);
        } else {
          return metaGraphsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public int getMetaGraphsCount() {
        if (metaGraphsBuilder_ == null) {
          return metaGraphs_.size();
        } else {
          return metaGraphsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef getMetaGraphs(int index) {
        if (metaGraphsBuilder_ == null) {
          return metaGraphs_.get(index);
        } else {
          return metaGraphsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public Builder setMetaGraphs(
          int index, com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef value) {
        if (metaGraphsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetaGraphsIsMutable();
          metaGraphs_.set(index, value);
          onChanged();
        } else {
          metaGraphsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public Builder setMetaGraphs(
          int index, com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef.Builder builderForValue) {
        if (metaGraphsBuilder_ == null) {
          ensureMetaGraphsIsMutable();
          metaGraphs_.set(index, builderForValue.build());
          onChanged();
        } else {
          metaGraphsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public Builder addMetaGraphs(com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef value) {
        if (metaGraphsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetaGraphsIsMutable();
          metaGraphs_.add(value);
          onChanged();
        } else {
          metaGraphsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public Builder addMetaGraphs(
          int index, com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef value) {
        if (metaGraphsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetaGraphsIsMutable();
          metaGraphs_.add(index, value);
          onChanged();
        } else {
          metaGraphsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public Builder addMetaGraphs(
          com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef.Builder builderForValue) {
        if (metaGraphsBuilder_ == null) {
          ensureMetaGraphsIsMutable();
          metaGraphs_.add(builderForValue.build());
          onChanged();
        } else {
          metaGraphsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public Builder addMetaGraphs(
          int index, com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef.Builder builderForValue) {
        if (metaGraphsBuilder_ == null) {
          ensureMetaGraphsIsMutable();
          metaGraphs_.add(index, builderForValue.build());
          onChanged();
        } else {
          metaGraphsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public Builder addAllMetaGraphs(
          java.lang.Iterable<? extends com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef> values) {
        if (metaGraphsBuilder_ == null) {
          ensureMetaGraphsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, metaGraphs_);
          onChanged();
        } else {
          metaGraphsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public Builder clearMetaGraphs() {
        if (metaGraphsBuilder_ == null) {
          metaGraphs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          metaGraphsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public Builder removeMetaGraphs(int index) {
        if (metaGraphsBuilder_ == null) {
          ensureMetaGraphsIsMutable();
          metaGraphs_.remove(index);
          onChanged();
        } else {
          metaGraphsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef.Builder getMetaGraphsBuilder(
          int index) {
        return getMetaGraphsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDefOrBuilder getMetaGraphsOrBuilder(
          int index) {
        if (metaGraphsBuilder_ == null) {
          return metaGraphs_.get(index);  } else {
          return metaGraphsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public java.util.List<? extends com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDefOrBuilder> 
           getMetaGraphsOrBuilderList() {
        if (metaGraphsBuilder_ != null) {
          return metaGraphsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(metaGraphs_);
        }
      }
      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef.Builder addMetaGraphsBuilder() {
        return getMetaGraphsFieldBuilder().addBuilder(
            com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef.getDefaultInstance());
      }
      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef.Builder addMetaGraphsBuilder(
          int index) {
        return getMetaGraphsFieldBuilder().addBuilder(
            index, com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef.getDefaultInstance());
      }
      /**
       * <pre>
       * One or more MetaGraphs.
       * </pre>
       *
       * <code>repeated .angel.MetaGraphDef meta_graphs = 2;</code>
       */
      public java.util.List<com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef.Builder> 
           getMetaGraphsBuilderList() {
        return getMetaGraphsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef, com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef.Builder, com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDefOrBuilder> 
          getMetaGraphsFieldBuilder() {
        if (metaGraphsBuilder_ == null) {
          metaGraphsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef, com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDef.Builder, com.tencent.angel.core.saver.MetaGraphProtos.MetaGraphDefOrBuilder>(
                  metaGraphs_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          metaGraphs_ = null;
        }
        return metaGraphsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:angel.SavedModel)
    }

    // @@protoc_insertion_point(class_scope:angel.SavedModel)
    private static final com.tencent.angel.core.saver.SavedModelProtos.SavedModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.angel.core.saver.SavedModelProtos.SavedModel();
    }

    public static com.tencent.angel.core.saver.SavedModelProtos.SavedModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SavedModel>
        PARSER = new com.google.protobuf.AbstractParser<SavedModel>() {
      public SavedModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SavedModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SavedModel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SavedModel> getParserForType() {
      return PARSER;
    }

    public com.tencent.angel.core.saver.SavedModelProtos.SavedModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_angel_SavedModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_angel_SavedModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034core/saver/saved_model.proto\022\005angel\032\033c" +
      "ore/saver/meta_graph.proto\"Z\n\nSavedModel" +
      "\022\"\n\032saved_model_schema_version\030\001 \001(\003\022(\n\013" +
      "meta_graphs\030\002 \003(\0132\023.angel.MetaGraphDefB2" +
      "\n\034com.tencent.angel.core.saverB\020SavedMod" +
      "elProtosP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tencent.angel.core.saver.MetaGraphProtos.getDescriptor(),
        }, assigner);
    internal_static_angel_SavedModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_angel_SavedModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_angel_SavedModel_descriptor,
        new java.lang.String[] { "SavedModelSchemaVersion", "MetaGraphs", });
    com.tencent.angel.core.saver.MetaGraphProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
