// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: servable/saved_model_bundle_source_adapter.proto

package com.tencent.angel.servable;

public final class SavedModelBundleSourceAdapterConfigProtos {
  private SavedModelBundleSourceAdapterConfigProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SavedModelBundleSourceAdapterConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:angel.SavedModelBundleSourceAdapterConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * A SessionBundleConfig.
     * FOR INTERNAL USE ONLY DURING TRANSITION TO SAVED_MODEL. WILL BE DEPRECATED.
     * TODO(b/32248363): Replace this field with the "real" field(s).
     * </pre>
     *
     * <code>optional .angel.SessionBundleConfig legacy_config = 1000;</code>
     */
    boolean hasLegacyConfig();
    /**
     * <pre>
     * A SessionBundleConfig.
     * FOR INTERNAL USE ONLY DURING TRANSITION TO SAVED_MODEL. WILL BE DEPRECATED.
     * TODO(b/32248363): Replace this field with the "real" field(s).
     * </pre>
     *
     * <code>optional .angel.SessionBundleConfig legacy_config = 1000;</code>
     */
    com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig getLegacyConfig();
    /**
     * <pre>
     * A SessionBundleConfig.
     * FOR INTERNAL USE ONLY DURING TRANSITION TO SAVED_MODEL. WILL BE DEPRECATED.
     * TODO(b/32248363): Replace this field with the "real" field(s).
     * </pre>
     *
     * <code>optional .angel.SessionBundleConfig legacy_config = 1000;</code>
     */
    com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfigOrBuilder getLegacyConfigOrBuilder();
  }
  /**
   * <pre>
   * Config proto for SavedModelBundleSourceAdapter.
   * </pre>
   *
   * Protobuf type {@code angel.SavedModelBundleSourceAdapterConfig}
   */
  public  static final class SavedModelBundleSourceAdapterConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:angel.SavedModelBundleSourceAdapterConfig)
      SavedModelBundleSourceAdapterConfigOrBuilder {
    // Use SavedModelBundleSourceAdapterConfig.newBuilder() to construct.
    private SavedModelBundleSourceAdapterConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SavedModelBundleSourceAdapterConfig() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SavedModelBundleSourceAdapterConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8002: {
              com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig.Builder subBuilder = null;
              if (legacyConfig_ != null) {
                subBuilder = legacyConfig_.toBuilder();
              }
              legacyConfig_ = input.readMessage(com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(legacyConfig_);
                legacyConfig_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.internal_static_angel_SavedModelBundleSourceAdapterConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.internal_static_angel_SavedModelBundleSourceAdapterConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig.class, com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig.Builder.class);
    }

    public static final int LEGACY_CONFIG_FIELD_NUMBER = 1000;
    private com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig legacyConfig_;
    /**
     * <pre>
     * A SessionBundleConfig.
     * FOR INTERNAL USE ONLY DURING TRANSITION TO SAVED_MODEL. WILL BE DEPRECATED.
     * TODO(b/32248363): Replace this field with the "real" field(s).
     * </pre>
     *
     * <code>optional .angel.SessionBundleConfig legacy_config = 1000;</code>
     */
    public boolean hasLegacyConfig() {
      return legacyConfig_ != null;
    }
    /**
     * <pre>
     * A SessionBundleConfig.
     * FOR INTERNAL USE ONLY DURING TRANSITION TO SAVED_MODEL. WILL BE DEPRECATED.
     * TODO(b/32248363): Replace this field with the "real" field(s).
     * </pre>
     *
     * <code>optional .angel.SessionBundleConfig legacy_config = 1000;</code>
     */
    public com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig getLegacyConfig() {
      return legacyConfig_ == null ? com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig.getDefaultInstance() : legacyConfig_;
    }
    /**
     * <pre>
     * A SessionBundleConfig.
     * FOR INTERNAL USE ONLY DURING TRANSITION TO SAVED_MODEL. WILL BE DEPRECATED.
     * TODO(b/32248363): Replace this field with the "real" field(s).
     * </pre>
     *
     * <code>optional .angel.SessionBundleConfig legacy_config = 1000;</code>
     */
    public com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfigOrBuilder getLegacyConfigOrBuilder() {
      return getLegacyConfig();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (legacyConfig_ != null) {
        output.writeMessage(1000, getLegacyConfig());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (legacyConfig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1000, getLegacyConfig());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig)) {
        return super.equals(obj);
      }
      com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig other = (com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig) obj;

      boolean result = true;
      result = result && (hasLegacyConfig() == other.hasLegacyConfig());
      if (hasLegacyConfig()) {
        result = result && getLegacyConfig()
            .equals(other.getLegacyConfig());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasLegacyConfig()) {
        hash = (37 * hash) + LEGACY_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getLegacyConfig().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Config proto for SavedModelBundleSourceAdapter.
     * </pre>
     *
     * Protobuf type {@code angel.SavedModelBundleSourceAdapterConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:angel.SavedModelBundleSourceAdapterConfig)
        com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.internal_static_angel_SavedModelBundleSourceAdapterConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.internal_static_angel_SavedModelBundleSourceAdapterConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig.class, com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig.Builder.class);
      }

      // Construct using com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (legacyConfigBuilder_ == null) {
          legacyConfig_ = null;
        } else {
          legacyConfig_ = null;
          legacyConfigBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.internal_static_angel_SavedModelBundleSourceAdapterConfig_descriptor;
      }

      public com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig getDefaultInstanceForType() {
        return com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig.getDefaultInstance();
      }

      public com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig build() {
        com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig buildPartial() {
        com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig result = new com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig(this);
        if (legacyConfigBuilder_ == null) {
          result.legacyConfig_ = legacyConfig_;
        } else {
          result.legacyConfig_ = legacyConfigBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig) {
          return mergeFrom((com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig other) {
        if (other == com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig.getDefaultInstance()) return this;
        if (other.hasLegacyConfig()) {
          mergeLegacyConfig(other.getLegacyConfig());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig legacyConfig_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig, com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig.Builder, com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfigOrBuilder> legacyConfigBuilder_;
      /**
       * <pre>
       * A SessionBundleConfig.
       * FOR INTERNAL USE ONLY DURING TRANSITION TO SAVED_MODEL. WILL BE DEPRECATED.
       * TODO(b/32248363): Replace this field with the "real" field(s).
       * </pre>
       *
       * <code>optional .angel.SessionBundleConfig legacy_config = 1000;</code>
       */
      public boolean hasLegacyConfig() {
        return legacyConfigBuilder_ != null || legacyConfig_ != null;
      }
      /**
       * <pre>
       * A SessionBundleConfig.
       * FOR INTERNAL USE ONLY DURING TRANSITION TO SAVED_MODEL. WILL BE DEPRECATED.
       * TODO(b/32248363): Replace this field with the "real" field(s).
       * </pre>
       *
       * <code>optional .angel.SessionBundleConfig legacy_config = 1000;</code>
       */
      public com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig getLegacyConfig() {
        if (legacyConfigBuilder_ == null) {
          return legacyConfig_ == null ? com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig.getDefaultInstance() : legacyConfig_;
        } else {
          return legacyConfigBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * A SessionBundleConfig.
       * FOR INTERNAL USE ONLY DURING TRANSITION TO SAVED_MODEL. WILL BE DEPRECATED.
       * TODO(b/32248363): Replace this field with the "real" field(s).
       * </pre>
       *
       * <code>optional .angel.SessionBundleConfig legacy_config = 1000;</code>
       */
      public Builder setLegacyConfig(com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig value) {
        if (legacyConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          legacyConfig_ = value;
          onChanged();
        } else {
          legacyConfigBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * A SessionBundleConfig.
       * FOR INTERNAL USE ONLY DURING TRANSITION TO SAVED_MODEL. WILL BE DEPRECATED.
       * TODO(b/32248363): Replace this field with the "real" field(s).
       * </pre>
       *
       * <code>optional .angel.SessionBundleConfig legacy_config = 1000;</code>
       */
      public Builder setLegacyConfig(
          com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig.Builder builderForValue) {
        if (legacyConfigBuilder_ == null) {
          legacyConfig_ = builderForValue.build();
          onChanged();
        } else {
          legacyConfigBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * A SessionBundleConfig.
       * FOR INTERNAL USE ONLY DURING TRANSITION TO SAVED_MODEL. WILL BE DEPRECATED.
       * TODO(b/32248363): Replace this field with the "real" field(s).
       * </pre>
       *
       * <code>optional .angel.SessionBundleConfig legacy_config = 1000;</code>
       */
      public Builder mergeLegacyConfig(com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig value) {
        if (legacyConfigBuilder_ == null) {
          if (legacyConfig_ != null) {
            legacyConfig_ =
              com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig.newBuilder(legacyConfig_).mergeFrom(value).buildPartial();
          } else {
            legacyConfig_ = value;
          }
          onChanged();
        } else {
          legacyConfigBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * A SessionBundleConfig.
       * FOR INTERNAL USE ONLY DURING TRANSITION TO SAVED_MODEL. WILL BE DEPRECATED.
       * TODO(b/32248363): Replace this field with the "real" field(s).
       * </pre>
       *
       * <code>optional .angel.SessionBundleConfig legacy_config = 1000;</code>
       */
      public Builder clearLegacyConfig() {
        if (legacyConfigBuilder_ == null) {
          legacyConfig_ = null;
          onChanged();
        } else {
          legacyConfig_ = null;
          legacyConfigBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * A SessionBundleConfig.
       * FOR INTERNAL USE ONLY DURING TRANSITION TO SAVED_MODEL. WILL BE DEPRECATED.
       * TODO(b/32248363): Replace this field with the "real" field(s).
       * </pre>
       *
       * <code>optional .angel.SessionBundleConfig legacy_config = 1000;</code>
       */
      public com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig.Builder getLegacyConfigBuilder() {
        
        onChanged();
        return getLegacyConfigFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * A SessionBundleConfig.
       * FOR INTERNAL USE ONLY DURING TRANSITION TO SAVED_MODEL. WILL BE DEPRECATED.
       * TODO(b/32248363): Replace this field with the "real" field(s).
       * </pre>
       *
       * <code>optional .angel.SessionBundleConfig legacy_config = 1000;</code>
       */
      public com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfigOrBuilder getLegacyConfigOrBuilder() {
        if (legacyConfigBuilder_ != null) {
          return legacyConfigBuilder_.getMessageOrBuilder();
        } else {
          return legacyConfig_ == null ?
              com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig.getDefaultInstance() : legacyConfig_;
        }
      }
      /**
       * <pre>
       * A SessionBundleConfig.
       * FOR INTERNAL USE ONLY DURING TRANSITION TO SAVED_MODEL. WILL BE DEPRECATED.
       * TODO(b/32248363): Replace this field with the "real" field(s).
       * </pre>
       *
       * <code>optional .angel.SessionBundleConfig legacy_config = 1000;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig, com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig.Builder, com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfigOrBuilder> 
          getLegacyConfigFieldBuilder() {
        if (legacyConfigBuilder_ == null) {
          legacyConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig, com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfig.Builder, com.tencent.angel.servable.SessionBundleConfigProtos.SessionBundleConfigOrBuilder>(
                  getLegacyConfig(),
                  getParentForChildren(),
                  isClean());
          legacyConfig_ = null;
        }
        return legacyConfigBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:angel.SavedModelBundleSourceAdapterConfig)
    }

    // @@protoc_insertion_point(class_scope:angel.SavedModelBundleSourceAdapterConfig)
    private static final com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig();
    }

    public static com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SavedModelBundleSourceAdapterConfig>
        PARSER = new com.google.protobuf.AbstractParser<SavedModelBundleSourceAdapterConfig>() {
      public SavedModelBundleSourceAdapterConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SavedModelBundleSourceAdapterConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SavedModelBundleSourceAdapterConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SavedModelBundleSourceAdapterConfig> getParserForType() {
      return PARSER;
    }

    public com.tencent.angel.servable.SavedModelBundleSourceAdapterConfigProtos.SavedModelBundleSourceAdapterConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_angel_SavedModelBundleSourceAdapterConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_angel_SavedModelBundleSourceAdapterConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0servable/saved_model_bundle_source_ada" +
      "pter.proto\022\005angel\032$servable/session_bund" +
      "le_config.proto\"Y\n#SavedModelBundleSourc" +
      "eAdapterConfig\0222\n\rlegacy_config\030\350\007 \001(\0132\032" +
      ".angel.SessionBundleConfigBI\n\032com.tencen" +
      "t.angel.servableB)SavedModelBundleSource" +
      "AdapterConfigProtosP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tencent.angel.servable.SessionBundleConfigProtos.getDescriptor(),
        }, assigner);
    internal_static_angel_SavedModelBundleSourceAdapterConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_angel_SavedModelBundleSourceAdapterConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_angel_SavedModelBundleSourceAdapterConfig_descriptor,
        new java.lang.String[] { "LegacyConfig", });
    com.tencent.angel.servable.SessionBundleConfigProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
